### ISSUE TITLE
Allow to filter items by parameters

### ISSUE THREAD

**Issue by markets** [Subgin/tonic#26]
So it will be easy to share 🌐 specific filtering by just copying the current URL:

```
https://my-collection.com?price_max=40&category=music
```

It should be quite feasible to implement with: [getParam](https://github.com/ralixjs/ralix/blob/master/docs/HELPERS_API.md#getparamparam) and [setParam](https://github.com/ralixjs/ralix/blob/master/docs/HELPERS_API.md#setparamparam-value) from Ralix.

High level:
- once a filter is applied, use `setParam(attribute, value)`
- on page load, use `getParam` to set `currentFilters` and apply filtering

**Comment by mlewis1** [comment]
Came here to suggest the same feature! (Ideally, making new filter selections in the UI would update the URL parameters _without_ a page reload, but even if that were not the case, this would still be a huge improvement to an already great framework.)

**Comment by markets** [comment]
@mlewis1 released as v0.10.0 and demo app updated 🚀
